export interface OAuthProvider {
  id: string;
  name: string;
  description: string;
  category: string;
  color: string;
  bgColor: string;
  icon: string; // SVG path or emoji fallback
  authUrl: string;
  tokenUrl: string;
  scopes: string[];
  scopeSeparator: string;
  supportsRefresh: boolean;
  tokenExpiry: string;
  usePKCE: boolean;
  extraAuthParams?: Record<string, string>;
}

export const PROVIDERS: OAuthProvider[] = [
  {
    id: "facebook",
    name: "Facebook",
    description: "Pages, posts, ads & insights",
    category: "Social Media",
    color: "#1877F2",
    bgColor: "#EBF5FF",
    icon: "facebook",
    authUrl: "https://www.facebook.com/v19.0/dialog/oauth",
    tokenUrl: "https://graph.facebook.com/v19.0/oauth/access_token",
    scopes: ["pages_manage_posts", "pages_read_engagement", "pages_show_list", "business_management"],
    scopeSeparator: ",",
    supportsRefresh: false,
    tokenExpiry: "60 days",
    usePKCE: false,
    extraAuthParams: { response_type: "code" },
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Business accounts, media & analytics",
    category: "Social Media",
    color: "#E1306C",
    bgColor: "#FDF2F8",
    icon: "instagram",
    authUrl: "https://api.instagram.com/oauth/authorize",
    tokenUrl: "https://api.instagram.com/oauth/access_token",
    scopes: ["instagram_business_basic", "instagram_business_manage_messages", "instagram_business_content_publish"],
    scopeSeparator: ",",
    supportsRefresh: false,
    tokenExpiry: "60 days",
    usePKCE: false,
  },
  {
    id: "google",
    name: "Google",
    description: "Gmail, Calendar, Drive & Sheets",
    category: "Productivity",
    color: "#4285F4",
    bgColor: "#EFF6FF",
    icon: "google",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    scopes: [
      "https://www.googleapis.com/auth/gmail.readonly",
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile",
    ],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "1 hour",
    usePKCE: true,
    extraAuthParams: { access_type: "offline", prompt: "consent" },
  },
  {
    id: "twitter",
    name: "Twitter / X",
    description: "Tweets, DMs & analytics",
    category: "Social Media",
    color: "#000000",
    bgColor: "#F9FAFB",
    icon: "twitter",
    authUrl: "https://twitter.com/i/oauth2/authorize",
    tokenUrl: "https://api.twitter.com/2/oauth2/token",
    scopes: ["tweet.read", "tweet.write", "users.read", "dm.read", "offline.access"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "2 hours",
    usePKCE: true,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Posts, company pages & analytics",
    category: "Social Media",
    color: "#0A66C2",
    bgColor: "#EFF6FF",
    icon: "linkedin",
    authUrl: "https://www.linkedin.com/oauth/v2/authorization",
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
    scopes: ["r_liteprofile", "r_emailaddress", "w_member_social", "rw_organization_admin"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "60 days",
    usePKCE: false,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Messages, channels & workspaces",
    category: "Messaging",
    color: "#4A154B",
    bgColor: "#FDF4FF",
    icon: "slack",
    authUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    scopes: ["channels:read", "channels:write", "chat:write", "users:read", "files:read"],
    scopeSeparator: ",",
    supportsRefresh: true,
    tokenExpiry: "12 hours",
    usePKCE: false,
  },
  {
    id: "github",
    name: "GitHub",
    description: "Repos, issues, PRs & actions",
    category: "Developer Tools",
    color: "#24292F",
    bgColor: "#F6F8FA",
    icon: "github",
    authUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    scopes: ["repo", "user", "read:org", "workflow"],
    scopeSeparator: " ",
    supportsRefresh: false,
    tokenExpiry: "No expiry",
    usePKCE: false,
  },
  {
    id: "discord",
    name: "Discord",
    description: "Servers, channels & bots",
    category: "Messaging",
    color: "#5865F2",
    bgColor: "#EDEFFF",
    icon: "discord",
    authUrl: "https://discord.com/api/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    scopes: ["identify", "email", "guilds", "guilds.join", "messages.read"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "7 days",
    usePKCE: false,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Pages, databases & workspaces",
    category: "Productivity",
    color: "#000000",
    bgColor: "#F7F7F7",
    icon: "notion",
    authUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    scopes: [],
    scopeSeparator: " ",
    supportsRefresh: false,
    tokenExpiry: "No expiry",
    usePKCE: false,
    extraAuthParams: { response_type: "code", owner: "user" },
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Payments, subscriptions & invoices",
    category: "Finance",
    color: "#635BFF",
    bgColor: "#F0EFFF",
    icon: "stripe",
    authUrl: "https://connect.stripe.com/oauth/authorize",
    tokenUrl: "https://connect.stripe.com/oauth/token",
    scopes: ["read_write"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "No expiry",
    usePKCE: false,
    extraAuthParams: { response_type: "code" },
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Videos, creator data & analytics",
    category: "Social Media",
    color: "#010101",
    bgColor: "#F9FAFB",
    icon: "tiktok",
    authUrl: "https://www.tiktok.com/v2/auth/authorize",
    tokenUrl: "https://open.tiktokapis.com/v2/oauth/token/",
    scopes: ["user.info.basic", "video.list", "user.info.stats"],
    scopeSeparator: ",",
    supportsRefresh: true,
    tokenExpiry: "24 hours",
    usePKCE: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM, contacts & marketing",
    category: "CRM",
    color: "#FF7A59",
    bgColor: "#FFF5F2",
    icon: "hubspot",
    authUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    scopes: ["crm.objects.contacts.read", "crm.objects.contacts.write", "crm.objects.deals.read"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "6 hours",
    usePKCE: false,
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email campaigns & audiences",
    category: "Marketing",
    color: "#FFE01B",
    bgColor: "#FFFEF0",
    icon: "mailchimp",
    authUrl: "https://login.mailchimp.com/oauth2/authorize",
    tokenUrl: "https://login.mailchimp.com/oauth2/token",
    scopes: [],
    scopeSeparator: " ",
    supportsRefresh: false,
    tokenExpiry: "No expiry",
    usePKCE: false,
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "Products, orders & customers",
    category: "E-commerce",
    color: "#96BF48",
    bgColor: "#F4FAF0",
    icon: "shopify",
    authUrl: "https://{shop}.myshopify.com/admin/oauth/authorize",
    tokenUrl: "https://{shop}.myshopify.com/admin/oauth/access_token",
    scopes: ["read_products", "write_products", "read_orders", "write_orders"],
    scopeSeparator: ",",
    supportsRefresh: false,
    tokenExpiry: "No expiry",
    usePKCE: false,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Bases, tables & records",
    category: "Productivity",
    color: "#18BFFF",
    bgColor: "#F0FAFE",
    icon: "airtable",
    authUrl: "https://airtable.com/oauth2/v1/authorize",
    tokenUrl: "https://airtable.com/oauth2/v1/token",
    scopes: ["data.records:read", "data.records:write", "schema.bases:read"],
    scopeSeparator: " ",
    supportsRefresh: true,
    tokenExpiry: "1 hour",
    usePKCE: true,
  },
];

export const CATEGORIES = [
  "All",
  "Social Media",
  "Productivity",
  "Messaging",
  "Developer Tools",
  "CRM",
  "Marketing",
  "E-commerce",
  "Finance",
];

export function getProvider(id: string): OAuthProvider | undefined {
  return PROVIDERS.find((p) => p.id === id);
}
